# Total training steps:
# - 1784 for batch_size = 32 and num_train_epochs = 2

experiment_name: distil_word_level-small_to_base-librispeech_clean_100h-full
lang_name: english
task: transcribe
method_distil: word_level
teacher_model_name_or_path: openai/whisper-small
student_model_name_or_path: openai/whisper-base
is_tokenizer_multilingual: True
model_dir: ./checkpoints/distil_word_level/whisper_small_to_base/librispeech_clean_100h/full
freeze_encoder: True
freeze_decoder: False
batch_size: 32
gradient_accumulation_steps: 1
gradient_checkpointing: False
dataset_name: librispeech_clean_100h
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 175
eval_steps: 350
generation_num_beams: 1
logging_steps: 175
save_steps: 350
num_train_epochs: 4

zero_shot_eval: False
eval_batch_size: 256
eval_accumulation_steps:
save_total_limit: 1
early_stopping_patience: 4
save_final_model: True

alpha_ce: 0.5
temperature: 1.0

smart_load: True
force_reprocess_dataset: False
eval_first_step: False
log_preds_to_wandb: True
log_raw_str: True
n_samples_per_wandb_logging_step: 16
