# With batch_size = 32 and num_train_epochs = 1:
# -> global_step = 340
experiment_name: exp_1-word_level-temperature_0
lang_name: english
task: transcribe
method_distil: word_level
teacher_model_name_or_path: openai/whisper-medium
student_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
model_dir: ./checkpoints/experiments/exp_1-word_level-temperature_0
freeze_encoder: True
freeze_decoder: False
batch_size: 32
gradient_accumulation_steps: 1
gradient_checkpointing: True
data_augmentation: False
dataset_name: ami_10h
force_reprocess_dataset: False
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 8
eval_steps: 56
generation_num_beams: 1
logging_steps: 56
save_steps: 560  # do not save the model
num_train_epochs: 0.5

zero_shot_eval: False
eval_batch_size:
eval_accumulation_steps: 1
save_total_limit: 2
early_stopping_patience: -1

alpha_ce: 0.
temperature: 0.0001

smart_load: True
eval_first_step: False
log_preds_to_wandb: True
log_raw_str: True
n_samples_per_wandb_logging_step: 16
