# Total training steps:
# - 5088 for batch_size = 64 and num_train_epochs = 3
# - 6782 for batch_size = 32 and num_train_epochs = 2

experiment_name: finetune-whisper_tiny-ami_100h
lang_name: english
task: transcribe
pretrained_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
model_dir: ./checkpoints/finetuning/whisper_tiny/ami_100h/
freeze_encoder: True
freeze_decoder: False
batch_size: 32
gradient_accumulation_steps: 1
gradient_checkpointing: True
dataset_name: ami_100h
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 600
eval_steps: 1200
generation_num_beams: 1
logging_steps: 600
save_steps: 1200
num_train_epochs: 2

zero_shot_eval: False
eval_batch_size: 512
eval_accumulation_steps:
save_total_limit:
early_stopping_patience:

smart_load: True
force_reprocess_dataset: False
eval_first_step: False
log_preds_to_wandb: True
log_raw_str: True
n_samples_per_wandb_logging_step: 8
