experiment_name: finetune-whisper_tiny_en-librispeech_clean_100h-freeze_encoder
lang_name: english
task: transcribe
pretrained_model_name_or_path: openai/whisper-tiny.en
is_tokenizer_multilingual: False
model_dir: ./checkpoints/finetuning/english_model/finetune-whisper_tiny_en-librispeech_clean_100h-freeze_encoder/
freeze_encoder: True
freeze_decoder: False
batch_size: 16
gradient_accumulation_steps: 2
gradient_checkpointing: True
data_augmentation: False
dataset_name: librispeech_clean_100h
force_reprocess_dataset: False
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 100
eval_steps: 500
generation_num_beams: 5
logging_steps: 250
save_steps: 500
save_total_limit:
num_train_epochs: 5
early_stopping_patience: 3
log_preds_to_wandb: True
