# Total training steps:
# - 340 for batch_size = 32 and num_train_epochs = 1

experiment_name: finetune-whisper_tiny-ami_10h-benchmark
lang_name: english
task: transcribe
pretrained_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
model_dir: ./checkpoints/finetuning/whisper_tiny/ami_10h-benchmark/
freeze_encoder: True
freeze_decoder: False
batch_size: 32
gradient_accumulation_steps: 1
gradient_checkpointing: False
dataset_name: ami_10h
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 17
eval_steps: 68
generation_num_beams: 1
logging_steps: 68
save_steps: 68
num_train_epochs: 1

zero_shot_eval: False
eval_batch_size: 256
eval_accumulation_steps:
save_total_limit:
early_stopping_patience: -1
save_final_model: False

smart_load: True
force_reprocess_dataset: False
eval_first_step: False
log_preds_to_wandb: True
log_raw_str: True
n_samples_per_wandb_logging_step: 8
