# Total training steps:
# - 3391 for batch_size = 32 and num_train_epochs = 1

experiment_name: distil_1_best-medium_prefinetuned_to_tiny-ami_100h-filtered-full
lang_name: english
task: transcribe
method_distil: seq_level_uniform
teacher_model_name_or_path: ./checkpoints/finetuning/whisper_medium/ami_100h_hpt_reference_teacher/checkpoint-3000
teacher_original_name: openai/whisper-medium
student_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
model_dir: ./checkpoints/distil_1_best/whisper_medium_prefinetuned_to_tiny/hpt/ami_100h-filtered-gzip-full
freeze_encoder: True
freeze_decoder: False
batch_size: 32
gradient_accumulation_steps: 1
gradient_checkpointing: False
dataset_name: ami_100h
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 300
eval_steps: 600
generation_num_beams: 1
logging_steps: 300
save_steps: 600
num_train_epochs: 4

zero_shot_eval: False
eval_batch_size: 256
eval_accumulation_steps:
save_total_limit: 2
early_stopping_patience: 3
save_final_model: True

alpha_ce: 0.
distillation_num_beams: 1
max_teacher_gzip_ratio: 1.50

smart_load: True
force_reprocess_dataset: False
eval_first_step: False
log_preds_to_wandb: True
log_raw_str: True
n_samples_per_wandb_logging_step: 16
