# Total training steps:
# - 2230 for batch_size = 64 and num_train_epochs = 5
# - 4460 for batch_size = 32 and num_train_epochs = 5
# - 2676 for batch_size = 32 and num_train_epochs = 3

experiment_name: distil_tac-medium_to_tiny-librispeech_clean_100h-word_level
lang_name: english
task: transcribe
method_distil: word_level
teacher_model_name_or_path: openai/whisper-medium
student_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
model_dir: ./checkpoints/distillation_tac/whisper_medium_to_tiny/librispeech_clean_100h/word_level/
freeze_encoder: True
freeze_decoder: False
batch_size: 32
gradient_accumulation_steps: 1
gradient_checkpointing: True
dataset_name: librispeech_clean_100h
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 100
eval_steps: 500
generation_num_beams: 1  # to speed up eval
logging_steps: 250
save_steps: 500
num_train_epochs: 3

zero_shot_eval: False
eval_batch_size:
eval_accumulation_steps:
save_total_limit:
early_stopping_patience: -1

alpha_ce: 0.5
temperature: 5.0

gamma_tac: 0.2
languages_to_preserve: [french]
method_tac: word_level

smart_load: True
force_reprocess_dataset: False
eval_first_step: True
log_preds_to_wandb: True
log_raw_str: True
n_samples_per_wandb_logging_step: 8
