experiment_name: whisper_tiny-librispeech_clean_100h-debug
lang_name: english
task: transcribe
pretrained_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
model_dir: ./checkpoints/finetuning/debug/whisper_tiny/librispeech_clean_100h/
freeze_encoder: True
freeze_decoder: False
batch_size: 16
gradient_accumulation_steps: 2
eval_accumulation_steps:
gradient_checkpointing: True
data_augmentation: False
dataset_name: librispeech_clean_100h
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 50
eval_steps: 300
generation_num_beams: 5
logging_steps: 150
save_steps: 300
save_total_limit: 2
num_train_epochs: 1
early_stopping_patience: 3

smart_load: True
force_reprocess_dataset: False
eval_first_step: True
log_preds_to_wandb: True
log_raw_str: True
n_samples_per_wandb_logging_step: 32
