# Total training steps:
# - 2230 for batch_size = 64 and num_train_epochs = 5
# - 4460 for batch_size = 32 and num_train_epochs = 5
experiment_name: finetune-whisper_tiny-librispeech_clean_100h-zero_shot
lang_name: english
task: transcribe
pretrained_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
model_dir: ./checkpoints/finetuning/whisper_tiny/librispeech_clean_100h-zero_shot/
freeze_encoder: True
freeze_decoder: False
batch_size: 32
gradient_accumulation_steps: 1
gradient_checkpointing: True
dataset_name: librispeech_clean_100h
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 200
eval_steps: 600
generation_num_beams: 1  # to speed up eval
logging_steps: 600
save_steps: 600
num_train_epochs: 5

zero_shot: True
eval_batch_size: 128
eval_accumulation_steps:
save_total_limit: 2
early_stopping_patience: 3

smart_load: True
force_reprocess_dataset: False
eval_first_step: True
log_preds_to_wandb: True
log_raw_str: True
n_samples_per_wandb_logging_step: 8
