# batch_size = 16 -> 478 steps
experiment_name: finetune-whisper_tiny-ami_10h
lang_name: english
task: transcribe
pretrained_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
model_dir: ./checkpoints/finetuning/whisper_tiny-ami_10h/
freeze_encoder: True
freeze_decoder: False
batch_size: 16
eval_batch_size: 256
gradient_accumulation_steps: 1
eval_accumulation_steps:
gradient_checkpointing: True
data_augmentation: False
dataset_name: ami_10h
force_reprocess_dataset: False
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 40
eval_steps: 100
generation_num_beams: 5
logging_steps: 50
save_steps: 100
save_total_limit: 2
num_train_epochs: 1
early_stopping_patience: -1

smart_load: True
eval_first_step: True
log_preds_to_wandb: True
log_raw_str: True
n_samples_per_wandb_logging_step: 32
