experiment_name: distil_whisper_base_to_tiny-ami-word_level
lang_name: english
task: transcribe
method: word_level
teacher_model_name_or_path: openai/whisper-base
student_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
model_dir: ./checkpoints/distillation/whisper_base_to_tiny/ami/word_level
freeze_encoder: True
freeze_decoder: False
batch_size: 4
gradient_accumulation_steps: 2
gradient_checkpointing: True
data_augmentation: False
dataset_name: ami
force_reprocess_dataset: False
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 50
eval_steps: 50
generation_num_beams: 1
logging_steps: 50
save_steps: 50
save_total_limit: 2
num_train_epochs: 0.25
early_stopping_patience: -1

ce_alpha: 0.5
temperature: 2.0

smart_load: True
log_preds_to_wandb: True
log_raw_str: True
