experiment_name: whisper_tiny-librispeech_100h-benchmark
lang_name: english
task: transcribe
pretrained_model_name_or_path: openai/whisper-tiny.en
model_dir: ./checkpoints/whisper_tiny-librispeech_100h/
freeze_encoder: True
freeze_decoder: False
batch_size: 16
gradient_accumulation_steps: 2
gradient_checkpointing: True
data_augmentation: False
dataset_name: librispeech_100h
force_reprocess_dataset: False
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 256
eval_steps: 500
generation_num_beams: 5
logging_steps: 250
save_steps: 500
save_total_limit:
num_train_epochs: 5
early_stopping_patience: -1
log_preds_to_wandb: True
