# Total training steps:
# - 2676 for batch_size = 32 and num_train_epochs = 3

experiment_name: distil_whisper_medium_to_tiny-librispeech_clean_100h-seq_level_k_best_ranked-k_5
lang_name: english
task: transcribe
method_distil: seq_level_k_best_ranked
teacher_model_name_or_path: openai/whisper-medium
student_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
model_dir: ./checkpoints/distillation/whisper_medium_to_tiny/librispeech_clean_100h/seq_level_k_best_ranked-k_5
freeze_encoder: True
freeze_decoder: False
batch_size: 32
gradient_accumulation_steps: 1
gradient_checkpointing: True
dataset_name: librispeech_clean_100h
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 130
eval_steps: 500
generation_num_beams: 1  # to speed up eval
logging_steps: 250
save_steps: 500
num_train_epochs: 3

alpha_ce: 0.5
distillation_num_beams: 5
beta_decay: 2.0

zero_shot_eval: False
eval_batch_size: 256
eval_accumulation_steps:
save_total_limit: 2
early_stopping_patience: 3

smart_load: True
force_reprocess_dataset: False
eval_first_step: False
log_preds_to_wandb: True
log_raw_str: True
n_samples_per_wandb_logging_step: 8
