# Total training steps:
# - 1784 for batch_size = 32 and num_train_epochs = 2

experiment_name: distil_word_level-medium_to_tiny-librispeech-alpha_5e-1_temp_1-no_freeze
lang_name: english
task: transcribe
method_distil: word_level
teacher_model_name_or_path: openai/whisper-medium
student_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
model_dir: ./checkpoints/distil_word_level/whisper_medium_to_tiny/librispeech/alpha_5e-1_temp_1-no_freeze
freeze_encoder: False
freeze_decoder: False
batch_size: 32
gradient_accumulation_steps: 1
gradient_checkpointing: True
dataset_name: librispeech_clean_100h
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 175
eval_steps: 350
generation_num_beams: 1
logging_steps: 175
save_steps: 350  # do not save the model during training
num_train_epochs: 2

zero_shot_eval: False
eval_batch_size: 256
eval_accumulation_steps:
save_total_limit:
early_stopping_patience:
save_final_model: True  # save the model only at the end of training

alpha_ce: 0.5
temperature: 1.0

smart_load: True
force_reprocess_dataset: False
eval_first_step: False
log_preds_to_wandb: True
log_raw_str: True
n_samples_per_wandb_logging_step: 16
