# Total training steps:
# - 3391 for batch_size = 32 and num_train_epochs = 1
# - 1696 for batch_size = 32 and num_train_epochs = 0.5

experiment_name: distil_word_level-finetuned_medium_to_tiny-full-from_pretrained_student
lang_name: english
task: transcribe
method_distil: word_level
teacher_model_name_or_path: checkpoints/finetuning/whisper_medium/ami_100h_hpt_reference_teacher/checkpoint-3000
student_model_name_or_path: checkpoints/finetuning/whisper_tiny/ami_100h/final
is_tokenizer_multilingual: True
model_dir: ./checkpoints/distil_word_level/whisper_finetuned_medium_to_tiny/full/from_pretrained_student
freeze_encoder: True
freeze_decoder: False
batch_size: 32
gradient_accumulation_steps: 1
gradient_checkpointing: False
dataset_name: ami_100h
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 150
eval_steps: 500
generation_num_beams: 1
logging_steps: 250
save_steps: 500
num_train_epochs: 0.5

zero_shot_eval: False
eval_batch_size: 256
eval_accumulation_steps:
save_total_limit: 3
early_stopping_patience: 3
save_final_model: True

alpha_ce: 0.5
temperature: 1

smart_load: True
force_reprocess_dataset: False
eval_first_step: False
log_preds_to_wandb: True
log_raw_str: True
n_samples_per_wandb_logging_step: 16
