# Total training steps:
# - 30 for batch_size = 32 and num_train_epochs = 10

experiment_name: distil_tac-whisper_base_to_tiny-word_level-debug
lang_name: english
task: transcribe
method_distil: word_level
teacher_model_name_or_path: openai/whisper-base
student_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
model_dir: ./checkpoints/distillation_tac/whisper_base_to_tiny/librispeech_debug/word_level
freeze_encoder: True
freeze_decoder: False
batch_size: 32
gradient_accumulation_steps: 1
gradient_checkpointing: True
dataset_name: librispeech_dummy
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 5
eval_steps: 10
generation_num_beams: 1
logging_steps: 10
save_steps: 10000  # do not save checkpoints
num_train_epochs: 10

zero_shot_eval: False
eval_batch_size: 256
eval_accumulation_steps:
save_total_limit: 2
early_stopping_patience: -1

alpha_ce: 0.5
temperature: 5.0

gamma_tac: 0.2
languages_to_preserve: [french]
method_tac: word_level

smart_load: True
log_preds_to_wandb: True
log_raw_str: True
n_samples_per_wandb_logging_step: 8
