experiment_name: pretrain_whisper_tiny-implicit_lm-debug
lang_name: english
task: transcribe
pretrained_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
model_dir: ./checkpoints/implicit_lm_experiment/debug/finetune_whisper_tiny-implicit_lm-debug/
freeze_encoder: True
freeze_decoder: False
batch_size: 4
gradient_accumulation_steps: 1
gradient_checkpointing: False
data_augmentation: True
dataset_name: librispeech_dummy
force_reprocess_dataset: False
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 20
eval_steps: 10
generation_num_beams: 1
logging_steps: 10
save_steps: 100
save_total_limit: 2
num_train_epochs: 1
early_stopping_patience: -1
smart_load: True
log_preds_to_wandb: True
experimental_train_implicit_lm: False
