experiment_name: finetune_whisper_tiny-librispeech-debug
lang_name: english
task: transcribe
pretrained_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
model_dir: ./checkpoints/finetuning/debug/finetune_whisper_tiny-librispeech-debug/
freeze_encoder: True
freeze_decoder: False
batch_size: 4
gradient_accumulation_steps: 1
gradient_checkpointing: False
data_augmentation: True
dataset_name: librispeech_dummy
force_reprocess_dataset: False
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 10
eval_steps: 5
generation_num_beams: 1
logging_steps: 5
save_steps: 10
save_total_limit: 2
num_train_epochs: 5
early_stopping_patience: -1
smart_load: True
log_preds_to_wandb: True
experimental_train_implicit_lm: False
