# Total training steps:
# - 3391 for batch_size = 32 and num_train_epochs = 1

experiment_name: finetune-whisper_medium-ami_100h
lang_name: english
task: transcribe
pretrained_model_name_or_path: openai/whisper-medium
is_tokenizer_multilingual: True
model_dir: ./checkpoints/finetuning/whisper_medium/ami_100h_hpt_reference_teacher
freeze_encoder: True
freeze_decoder: False
batch_size: 16
gradient_accumulation_steps: 2
gradient_checkpointing: False
dataset_name: ami_100h
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 300
eval_steps: 600
generation_num_beams: 1
logging_steps: 300
save_steps: 600
num_train_epochs: 1

zero_shot_eval: False
eval_batch_size: 128
eval_accumulation_steps:
save_total_limit: 2
early_stopping_patience:
save_final_model: True

smart_load: True
force_reprocess_dataset: False
eval_first_step: False
log_preds_to_wandb: True
log_raw_str: True
n_samples_per_wandb_logging_step: 16
