# Total training steps:
# - 3391 for batch_size = 32 and num_train_epochs = 1

experiment_name: finetune_ewc-whisper_tiny-ami_100h-lambda_1e-2
lang_name: english
task: transcribe
pretrained_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
model_dir: ./checkpoints/finetune_ewc/whisper_tiny/ami_100h-lambda_1e-2/
freeze_encoder: True
freeze_decoder: False
batch_size: 32
gradient_accumulation_steps: 1
gradient_checkpointing: False
dataset_name: ami_100h
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 300
eval_steps: 600
generation_num_beams: 1
logging_steps: 300
save_steps: 6000  # don't save
num_train_epochs: 1

zero_shot_eval: False
eval_batch_size: 256
eval_accumulation_steps:
save_total_limit:
early_stopping_patience:
save_final_model: True

dirpath_ewc: checkpoints/whisper-tiny/english/transcribe/ami_100h/train
lambda_ewc: 0.01

smart_load: True
force_reprocess_dataset: False
eval_first_step: False
log_preds_to_wandb: True
log_raw_str: True
n_samples_per_wandb_logging_step: 16
