# Total training steps:
# - 5088 for batch_size = 64 and num_train_epochs = 3
# - 6782 for batch_size = 32 and num_train_epochs = 2
experiment_name: distil_whisper_medium_to_tiny-ami_100h-seq_level_ranked-k_3
lang_name: english
task: transcribe
method_distil: seq_level_ranked
teacher_model_name_or_path: openai/whisper-medium
student_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
model_dir: ./checkpoints/distillation/whisper_medium_to_tiny/ami_100h/seq_level_ranked-k_3
freeze_encoder: True
freeze_decoder: False
batch_size: 32
gradient_accumulation_steps: 1
gradient_checkpointing: False
dataset_name: ami_100h
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 600
eval_steps: 1200
generation_num_beams: 1
logging_steps: 600
save_steps: 1200
num_train_epochs: 2

zero_shot_eval: False
eval_batch_size: 256
eval_accumulation_steps: 5
save_total_limit:
early_stopping_patience:

alpha_ce: 0.5
distillation_num_beams: 3
beta_decay: 2.0

smart_load: True
eval_first_step: False
log_preds_to_wandb: True
log_raw_str: True
n_samples_per_wandb_logging_step: 16
