experiment_name: distil_tac=whisper_base_to_tiny-word_level-debug
lang_name: english
task: transcribe
method: word_level
teacher_model_name_or_path: openai/whisper-base
student_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
model_dir: ./checkpoints/distillation_tac/whisper_base_to_tiny/librispeech_debug/word_level
freeze_encoder: True
freeze_decoder: False
batch_size: 8
gradient_accumulation_steps: 2
gradient_checkpointing: True
data_augmentation: False
dataset_name: librispeech_dummy
force_reprocess_dataset: False
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 5
eval_steps: 5
generation_num_beams: 3
logging_steps: 5
save_steps: 100
num_train_epochs: 10

zero_shot: False
eval_batch_size: 256
eval_accumulation_steps:
save_total_limit: 2
early_stopping_patience: -1

alpha_ce: 0.5
temperature: 2.0

gamma_tac: 0.2
languages_to_preserve: [french]
method_tac: word_level

smart_load: True
log_preds_to_wandb: True
log_raw_str: True
n_samples_per_wandb_logging_step: 32
