# Total training steps:
# - 340 for batch_size = 32 and num_train_epochs = 1

experiment_name: distil_whisper_medium_to_tiny-ami_10h-seq_level_uniform-k_3
lang_name: english
task: transcribe
method_distil: seq_level_uniform
teacher_model_name_or_path: openai/whisper-medium
student_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
model_dir: ./checkpoints/distillation/whisper_medium_to_tiny/ami_10h/seq_level_uniform-k_3
freeze_encoder: True
freeze_decoder: False
batch_size: 32
gradient_accumulation_steps: 1
gradient_checkpointing: True
dataset_name: ami_10h
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 34
eval_steps: 68
generation_num_beams: 1
logging_steps: 68
save_steps: 68
num_train_epochs: 1

zero_shot_eval: False
eval_batch_size: 256
eval_accumulation_steps: 5
save_total_limit:
early_stopping_patience:

alpha_ce: 0.5
distillation_num_beams: 3

smart_load: True
eval_first_step: False
log_preds_to_wandb: True
log_raw_str: True
n_samples_per_wandb_logging_step: 8
