# Total training steps:
# - 3391 for batch_size = 32 and num_train_epochs = 1
# - 10173 for batch_size = 32 and num_train_epochs = 3

experiment_name: distil_1_best-medium_to_tiny-ami_100h-3_epochs
lang_name: english
task: transcribe
method_distil: seq_level_uniform
teacher_model_name_or_path: openai/whisper-medium
student_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
model_dir: ./checkpoints/distil_1_best/whisper_medium_to_tiny/ami_100h-3_epochs
freeze_encoder: True
freeze_decoder: False
batch_size: 32
gradient_accumulation_steps: 1
gradient_checkpointing: False
dataset_name: ami_100h
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 300
eval_steps: 1000
generation_num_beams: 1
logging_steps: 500
save_steps: 3000
num_train_epochs: 3

zero_shot_eval: False
eval_batch_size: 256
eval_accumulation_steps:
save_total_limit:
early_stopping_patience:
save_final_model: True

alpha_ce: 0.
distillation_num_beams: 1

smart_load: True
force_reprocess_dataset: False
eval_first_step: False
log_preds_to_wandb: True
log_raw_str: True
n_samples_per_wandb_logging_step: 16
