lang_name: english
task: transcribe
method: seq_level_k_best_uniform
teacher_model_name_or_path: openai/whisper-medium
student_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
freeze_encoder: True
freeze_decoder: False
batch_size: 32
gradient_accumulation_steps: 2
eval_accumulation_steps:
gradient_checkpointing: True
data_augmentation: False
dataset_name: ami_10h
optim: adamw_torch
warmup_steps: 25
eval_steps: 50
generation_num_beams: 5
logging_steps: 25
save_steps: 50
save_total_limit: 2
num_train_epochs: 0.5
early_stopping_patience: -1
