experiment_name: word_level-sequential_hpt-3_2
lang_name: english
task: transcribe
method: word_level
teacher_model_name_or_path: openai/whisper-medium
student_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
model_dir: ./checkpoints/distillation/whisper_medium_to_tiny/ami_10h/word_level-hpt/hpt-3_2
freeze_encoder: True
freeze_decoder: False
batch_size: 16
gradient_accumulation_steps: 4
eval_accumulation_steps: 40
gradient_checkpointing: True
data_augmentation: False
dataset_name: ami_10h
force_reprocess_dataset: False
optim: adamw_torch
warmup_steps: 50
eval_steps: 50
generation_num_beams: 5
logging_steps: 50
save_steps: 100000  # do not save the model
save_total_limit: 2
num_train_epochs: 0.5
early_stopping_patience: -1

smart_load: True
log_preds_to_wandb: True
log_raw_str: True
n_samples_per_wandb_logging_step: 16


# ======  HPT  ======
is_hpt: True
learning_rate: 1e-4  # optimized
temperature: 5  # optimized
ce_alpha: 0.5  # current
