experiment_name: train-with-normalization
lang_name: english
lang_id: en
pretrained_model_name_or_path: openai/whisper-tiny.en
model_dir: ./checkpoints
batch_size: 16
gradient_accumulation_steps: 2
gradient_checkpointing: True
data_augmentation: False
dataset_name: librispeech
force_reprocess_dataset: False
optim: adamw_torch
learning_rate: 1e-4
warmup_steps: 256
eval_steps: 250
generation_num_beams: 5
logging_steps: 100
save_steps: 250
num_train_epochs: 5
early_stopping_patience: 3
