experiment_name: whisper_tiny-librispeech_dummy
lang_name: english
lang_id: en
pretrained_model_name_or_path: openai/whisper-tiny.en
model_dir: ./checkpoints/librispeech_dummy/
batch_size: 4
gradient_accumulation_steps: 1
gradient_checkpointing: True
data_augmentation: False
dataset_name: librispeech_dummy
force_reprocess_dataset: False
optim: adamw_torch
learning_rate: 1e-4
warmup_steps: 20
eval_steps: 10
generation_num_beams: 1
logging_steps: 10
save_steps: 100
num_train_epochs: 10
early_stopping_patience: 3
log_preds_to_wandb: True
