experiment_name: whisper_small_en-librispeech_100h
lang_name: english
task: transcribe
pretrained_model_name_or_path: openai/whisper-small.en
model_dir: ./checkpoints/whisper_small_en-librispeech_100h/
freeze_encoder: True
freeze_decoder: False
batch_size: 16
gradient_accumulation_steps: 2
gradient_checkpointing: True
data_augmentation: False
dataset_name: librispeech_100h
force_reprocess_dataset: True  # TEMP
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 256
eval_steps: 200
generation_num_beams: 5
logging_steps: 100
save_steps: 200
save_total_limit: 2
num_train_epochs: 2
early_stopping_patience: 3
log_preds_to_wandb: True
