# Number of training examples: 28539
# Number of training steps for:
# - 2676 for batch_size = 16 and num_train_epochs = 3

experiment_name: distil_whisper_medium_to_tiny-librispeech_clean_100h-word_level
lang_name: english
task: transcribe
method_distil: word_level
teacher_model_name_or_path: openai/whisper-medium
student_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
model_dir: ./checkpoints/distillation/whisper_medium_to_tiny/librispeech_clean_100h/word_level/
freeze_encoder: True
freeze_decoder: False
batch_size: 16
gradient_accumulation_steps: 1
gradient_checkpointing: True
dataset_name: librispeech_clean_100h
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 125
eval_steps: 250
generation_num_beams: 1
logging_steps: 250
save_steps: 250
num_train_epochs: 3

alpha_ce: 0.5
temperature: 5.0

zero_shot: False
eval_batch_size: 256
eval_accumulation_steps:
save_total_limit:
early_stopping_patience: 3

smart_load: True
log_preds_to_wandb: True
log_raw_str: True
n_samples_per_wandb_logging_step: 8
