# Total training steps:
# - 1784 for batch_size = 32 and num_train_epochs = 2

experiment_name: whisper_tiny-librispeech_clean_100h-reference_for_distil
lang_name: english
task: transcribe
pretrained_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
model_dir: ./checkpoints/finetuning/whisper_tiny/librispeech_clean_100h/reference_for_distil/
freeze_encoder: False
freeze_decoder: False
batch_size: 32
gradient_accumulation_steps: 1
gradient_checkpointing: False
dataset_name: librispeech_clean_100h
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 175
eval_steps: 350
generation_num_beams: 1
logging_steps: 175
save_steps: 350
num_train_epochs: 2

zero_shot_eval: False
eval_batch_size: 256
eval_accumulation_steps:
save_total_limit:
early_stopping_patience:
save_final_model: True  # save the model only at the end of training

smart_load: True
force_reprocess_dataset: False
eval_first_step: False
log_preds_to_wandb: True
log_raw_str: True
n_samples_per_wandb_logging_step: 16
