# Total training steps:
# - 30 for batch_size = 32 and num_train_epochs = 10

experiment_name: finetune_ewc-tiny-librispeech_dummy-debug
lang_name: english
task: transcribe
pretrained_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
model_dir: ./checkpoints/finetune_ewc/whisper_tiny/librispeech_dummy
freeze_encoder: True
freeze_decoder: False
batch_size: 32
gradient_accumulation_steps: 1
gradient_checkpointing: False
dataset_name: librispeech_dummy
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 5
eval_steps: 10
generation_num_beams: 1
logging_steps: 10
save_steps: 10000  # do not save checkpoints
num_train_epochs: 10

eval_batch_size: 512
eval_accumulation_steps:
save_total_limit:
early_stopping_patience: -1
save_final_model: False

dirpath_ewc: checkpoints/whisper-tiny/french/transcribe/mls_french/validation
lambda_ewc: 0.5

smart_load: True
force_reprocess_dataset: False
eval_first_step: False
log_preds_to_wandb: True
log_raw_str: True
n_samples_per_wandb_logging_step: 8
