experiment_name: distil_whisper_base_to_tiny-ami_10h-seq_level_mode
lang_name: english
task: transcribe
method: seq_level_mode
teacher_model_name_or_path: openai/whisper-base
student_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
model_dir: ./checkpoints/distillation/whisper_base_to_tiny/ami_10h/seq_level_mode
freeze_encoder: True
freeze_decoder: False
batch_size: 16
gradient_accumulation_steps: 2
gradient_checkpointing: True
eval_accumulation_steps: 200
data_augmentation: False
dataset_name: ami_10h
force_reprocess_dataset: False
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 50
eval_steps: 50
generation_num_beams: 3
logging_steps: 50
save_steps: 50
save_total_limit: 2
num_train_epochs: 1
early_stopping_patience: 3

ce_alpha: 0.5
distillation_num_beams: 3

smart_load: True
log_preds_to_wandb: True
log_raw_str: True
n_samples_per_wandb_logging_step: 8
