experiment_name: distil_whisper_base_to_tiny-word_level-seq_level_mode-debug
lang_name: english
task: transcribe
method: seq_level_mode
teacher_model_name_or_path: openai/whisper-base
student_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
model_dir: ./checkpoints/distillation/whisper_base_to_tiny/librispeech_debug/seq_level_mode
freeze_encoder: True
freeze_decoder: False
batch_size: 16
gradient_accumulation_steps: 4
gradient_checkpointing: True
data_augmentation: False
dataset_name: librispeech_dummy
force_reprocess_dataset: False
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 5
eval_steps: 1
generation_num_beams: 1
logging_steps: 1
save_steps: 10
save_total_limit: 2
num_train_epochs: 1
early_stopping_patience: -1

ce_alpha: 0.5
distillation_num_beams: 3

smart_load: True
log_preds_to_wandb: True
log_raw_str: True
