experiment_name: whisper_medium-librispeech_clean_100h
lang_name: english
task: transcribe
pretrained_model_name_or_path: openai/whisper-medium
is_tokenizer_multilingual: True
model_dir: ./checkpoints/finetuning/whisper_medium/librispeech_clean_100h/
freeze_encoder: True
freeze_decoder: False
batch_size: 16
gradient_accumulation_steps: 2
gradient_checkpointing: False
data_augmentation: False
dataset_name: librispeech_clean_100h
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 100
eval_steps: 500
generation_num_beams: 1
logging_steps: 250
save_steps: 500
num_train_epochs: 3

zero_shot_eval: False
eval_batch_size: 128
eval_accumulation_steps:
save_total_limit: 2
early_stopping_patience: 3
save_final_model: False

smart_load: True
force_reprocess_dataset: False
eval_first_step: False
log_preds_to_wandb: True
log_raw_str: True
n_samples_per_wandb_logging_step: 16
