# Total training steps:
# - 340 for batch_size = 32 and num_train_epochs = 1
# - 1020 for batch_size = 32 and num_train_epochs = 3

experiment_name: finetune-whisper_tiny-ami_10h
lang_name: english
task: transcribe
pretrained_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
model_dir: ./checkpoints/finetuning/whisper_tiny/ami_10h/
freeze_encoder: True
freeze_decoder: False
batch_size: 32
gradient_accumulation_steps: 1
gradient_checkpointing: False
dataset_name: ami_10h
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 100
eval_steps: 20
generation_num_beams: 1
logging_steps: 100
save_steps: 200
num_train_epochs: 3

zero_shot_eval: False
eval_batch_size: 256
eval_accumulation_steps:
save_total_limit:
early_stopping_patience:
save_final_model: False

smart_load: True
force_reprocess_dataset: False
eval_first_step: False
log_preds_to_wandb: True
log_raw_str: True
n_samples_per_wandb_logging_step: 8
