# Total training steps:
# - 339 for batch_size = 32 and num_train_epochs = 1

experiment_name: distil_whisper_medium_to_tiny-ami_10h-word_level
lang_name: english
task: transcribe
method_distil: word_level
teacher_model_name_or_path: openai/whisper-medium
student_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
model_dir: ./checkpoints/distillation/whisper_medium_to_tiny/ami_10h/word_level
freeze_encoder: True
freeze_decoder: False
batch_size: 16
gradient_accumulation_steps: 2
gradient_checkpointing: True
data_augmentation: False
dataset_name: ami_10h
force_reprocess_dataset: False
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 16
eval_steps: 67
generation_num_beams: 1  # to speed up training
logging_steps: 67
save_steps: 67
num_train_epochs: 1

zero_shot_eval: False
eval_batch_size:
eval_accumulation_steps: 50
save_total_limit: 2
early_stopping_patience: 3
save_final_model: False

alpha_ce: 0.5
temperature: 5.0

smart_load: True
eval_first_step: False
log_preds_to_wandb: True
log_raw_str: True
n_samples_per_wandb_logging_step: 8
