# With batch_size = 32 and num_train_epochs = 0.5:
# -> global_step = 170
experiment_name: exp_2-seq_level_uniform-alpha_1
lang_name: english
task: transcribe
method_distil: seq_level_uniform
teacher_model_name_or_path: openai/whisper-medium
student_model_name_or_path: openai/whisper-tiny
is_tokenizer_multilingual: True
model_dir: ./checkpoints/experiments/exp_2-seq_level_uniform-alpha_1
freeze_encoder: True
freeze_decoder: False
batch_size: 32
gradient_accumulation_steps: 1
gradient_checkpointing: False
dataset_name: ami_10h
force_reprocess_dataset: False
optim: adamw_torch
learning_rate: 1e-5
warmup_steps: 8
eval_steps: 56
generation_num_beams: 1
logging_steps: 56
save_steps: 560  # do not save the model
num_train_epochs: 0.5

zero_shot_eval: False
eval_batch_size: 256
eval_accumulation_steps:
save_total_limit: 2
early_stopping_patience: -1

alpha_ce: 1.
distillation_num_beams: 1  # arbitrary as alpha_ce = 0

smart_load: True
eval_first_step: False
log_preds_to_wandb: True
log_raw_str: True
n_samples_per_wandb_logging_step: 16
